language: java
services:
  - xvfb
  - mysql
addons:
  sauce_connect:
    username: "esteban_cervera"
    access_key: "0706ac1c-19d9-450a-a786-a5f40767e103"
before_script:
  - "export DISPLAY=:99.0"
before_install:
  - mysql -u root --password="" < scripts/setup.sql
jobs:
  include:
    - stage: "Tests" # naming the Tests stage
      name: "Unit Tests" # names the first Tests stage job
      script: mvn -Dtest=TestDAOMySql test
    - script: mvn -Dtest=TestAlumnoOracleSQL test
      name: "Integration Tests" # names the second Tests stage job
    - script: mvn -Dtest=AllTests test
      name: "Functional Tests"
