language: java
services:
  - xvfb
  - mysql

before_script:
  - "export DISPLAY=:99.0"
before_install:
  - mysql -u root --password="" < scripts/setup.sql
jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      install: skip
      script: mvn -Dtest=TestDAOMySql test
    - script: mvn -Dtest=TestAlumnoOracleSQL test
      name: "Integration Tests"
    - script: mvn -Dtest=AllTests test
      name: "Functional Tests"
      install: skip
      addons:
        sauce_connect:
          username: "esteban_cervera"
          access_key: "0706ac1c-19d9-450a-a786-a5f40767e103"
